# k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-playground-ingress
  namespace: dev
spec:
  rules:
  - host: app.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wil-playground-svc
            port:
              number: 8888