apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev # Target namespace
spec:
  type: ClusterIP 
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 80 # Service receives traffic on port 80
      targetPort: 8888 # Routes to the container's port