apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-web-app # Must match the label in deployment.yaml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Must match the containerPort in deployment.yaml
      nodePort: 30000
  type: LoadBalancer # Or ClusterIP, depending on your needs